### ISSUE TITLE
TBD: Looser coupling between L2 blocks and L1 origin

### ISSUE THREAD

**Issue by alfonso-op** [ethereum-optimism/specs#316]
> Amend chain derivation rules such that not every L1 block needs to serve as a unique origin for L2 blocks. Instead, the L1 origin should be able to represent a range of L1 blocks, allowing L2 block times to be better decoupled from the L1

This capability may best be built leveraging the proposed deposit queue (see [spec](https://github.com/ethereum-optimism/specs/pull/82)).

Additional context in [this discussion thread](https://github.com/ethereum-optimism/specs/discussions/241#discussioncomment-10052249).

Note: this is not a must for Holocene, hence P2 priority. We could try to at least implement and include the deposit queue in Holocene so we can target the L2/L1 decoupling in the subsequent hard fork.

**Comment by BlocksOnAChain** [comment]
We might want to consider if this should be a P1, based on internal chats we had during planning. @sebastianst @roberto-bayardo  - let's discuss it on the Kick-off call.

**Comment by sebastianst** [comment]
This will surely not make it into Holocene, changing accordingly.

**Comment by tynes** [comment]
Replaced by https://github.com/ethereum-optimism/specs/issues/416
