### ISSUE TITLE
MTCannon: Tweak spec

### ISSUE THREAD

**Issue by mbaxter** [ethereum-optimism/specs#425]
## Description

This issue tracks some small changes to MTCannon that require spec updates. 

- As part of [this issue](https://github.com/ethereum-optimism/optimism/issues/11977), thread validity checks are made more specific,  so we should update the "Exceptions" section [here](https://github.com/ethereum-optimism/specs/blob/8e29d72b3ca4b380f20ad9df79c3a0a64f81a0b6/specs/experimental/cannon-fault-proof-vm-mt.md#L511-L513) to drop the first bullet point
- Incorporate changes from https://github.com/ethereum-optimism/optimism/pull/12569
  - Document noop syscalls lseek, rlimit
  - Update `clock_gettime` math to add use WordSize bytes instead of 4

**Comment by Inphi** [comment]
@mbaxter This overlaps with https://github.com/ethereum-optimism/optimism/issues/12253. Should we merge both issues?

**Comment by mbaxter** [comment]
I was thinking we could tweak the current spec to use some architecture-specific constants so that it would be mostly generic across 32- and 64-bit.  But I still think we probably want an isolated PR that swaps the non-generic parts like syscall numbers to the 64-bit version.  So, I tend to think we should keep them separate.

I can go ahead and wrap up these changes and close out this ticket so we can move on to the 64-bit-specific updates.

**Comment by Inphi** [comment]
The MT-Cannon spec is detached from singlethreaded Cannon. Since MT-Cannon is also going to be 64-bits with no support for 32-bit MT-Cannon, I think it'll be better to have the MT-Cannon spec specific to MIPS64.

**Comment by mbaxter** [comment]
Right - I just meant that it would be cleaner to do the conversion from 32 -> 64 in 1 isolated PR.  Making the spec more generic first just makes the conversion PR smaller.  But its not really a big deal either way.

**Comment by Inphi** [comment]
Gotcha. That's OK. That would be easier to review.
