### ISSUE TITLE
Proof Hints: Update New Hint to use Blockhash over Block Number

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/specs#439]
https://github.com/ethereum-optimism/specs/pull/438 introduces new hints that use a block number rather than a block hash. All of the existing hints operate on a block hash. We should update to be consistent and use block hashes when possible. This will also give a consistency guarantee, since a block by block number is subject to change via a reorg

See https://github.com/ethereum-optimism/specs/pull/438/files#r1814122088

cc @ajsutton @clabby

**Comment by meyer9** [comment]
opened a pr here: https://github.com/ethereum-optimism/specs/pull/442
