### ISSUE TITLE
Research Area: Blob Stitching

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/specs#74]
With the release of ecotone, it is expected that a batch cannot be larger than a single blob. For a 4844 tx that has multiple blobs, each blob is its own independent data, each must contain its own batch. It should be possible to have a batch that spans between blobs, we are calling this "blob stitching" as the derivation pipeline stitches together blobs in the same 4844 tx and attempts to read the data all together.

**Comment by protolambda** [comment]
We discussed this with the analytics/product folks and including multiple blobs per tx is definitely on our radar. It can be done without protocol changes; we already retrieve all of the referenced blobs, and have a way of stitching packets together. We can simply use the channel-frames to separate the data into blobs, the blob contents do not have to be literally concatenated.
