### ISSUE TITLE
Compatibility between interop chain ID and batch inbox convention

### ISSUE THREAD

**Issue by mds1** [ethereum-optimism/specs#94]
Currently the interop spec allows 256 bit chain IDs. The current convention (not requirement) for the batch inbox address is `0xFF00...{chainId}`. These are not compatible, as the batch inbox address only can fit chain IDs up to 19 bytes because addresses are 20 bytes. 

**This is currently not a big problem, and this issue is low priority**, because:
1. The batch inbox address is only a convention, so chains with chain IDs larger than 19 bytes can choose an arbitrary batch inbox address. But we don't yet spec out what requirements (if any) that address should have.
2. From my research, no chain IDs are currently large enough for this to be a problem. However, some OP Stack chains do not follow the batch inbox convention anyway.

So one consideration here is: should we enforce a batch inbox convention? Doing so would be a nice property, and we may want to spec out the required work to make this convention into a requirement.

Regardless, possible solutions to the existing incompatbility are discussed below:

## Shrink max allowable chain ID

[EIP-2294](https://eips.ethereum.org/EIPS/eip-2294) proposed a max chain ID of `floor(MAX_UINT64 / 2) - 36`. This value was chosen to prevent overflow of a uint64 when calculating the v-component of a signature as `{0,1} + CHAIN_ID * 2 + 35` per [EIP-155](https://eips.ethereum.org/EIPS/eip-155). Many popular tools, like MetaMask, [only support](https://gist.github.com/rekmarks/a47bd5f2525936c4b8eee31a16345553) chain IDs that are within the javascript `Number.MAX_SAFE_INTEGER` based on the same v-component calculation (resulting in ~4e15, below this proposed max).

This is my preferred solution because (1) it fixes the issue with minimal work, (2) mitigates the risk of OP Stack chains not supporting popular tools, and (3) can be expanded to a larger value in the future when needed.

A factor in this proposal becoming stagnant was because it prevents an easy way for chains to pick a unique chain ID through a process like `keccak256("myUniqueChainName")`. This is a good point, but we already do not do this, and we can expand allowable chain ID and change the convention in the future if this becomes necessary/desirable.

## Change Batch Inbox Convention

Since we only have 20 bytes to work with, the new batch inbox address convention have to be something like `keccak256(schemeVersion, chainId)[:20]`. This would require changes to op-node so it can read from two batch inbox addresses: the legacy address, and a new address. It also makes it harder to look at a batch inbox address and back out the chain it's for, but this can is solved by the superchain-registry anyway

## Do Nothing

Because this is just a convention, and not enforced, the status quo is ok—for chains that cannot meet the convention, they just choose a different, arbitrary batch inbox address. This should still be documented in the spec somewhere, e.g. in this case does the address still need to start with `0xFF`?

**Comment by mds1** [comment]
## Assumptions and Requirements

- Chain IDs are assumed to be unique
- Batch inbox address must be unique per chain
- Batch inbox address must be deterministic 
- Maybe: Forward compatibility with https://github.com/ethereum-optimism/specs/issues/221

## Proposal

- Initial scheme is version 0
- Batch inbox address is `versionByte || keccak256(bytes32(chainId))[:19]`, where `||` denotes concatenation and `chainId` is a uint256

This supports 256 iterations, and makes the version extractable from the address.

## Example:

For Chain ID 123, we first compute the hash to be `0x5569044719a1ec3b04d0afa9e7a5310c7c0473331d13dc9fafe143b2c4e8148a`

- Solidity: `keccak256(bytes.concat(bytes32(uint256(123))))`
- Cast: `cast keccak 0x000000000000000000000000000000000000000000000000000000000000007b`

Next we take the first 19 bytes of the hash: `0x5569044719a1ec3b04d0afa9e7a5310c7c0473`

Then we perform the concatenation with version 0 to get a batch inbox address of `0x005569044719a1ec3b04d0afa9e7a5310c7c0473`

## Questions

1. If this convention is agreed on, do we want existing chains to migrate towards this, or do we only use this convention for new chains going forward, e.g. as part of the OP Stack Manager (https://github.com/ethereum-optimism/specs/pull/236). I lean towards not migrating as it's much simpler, since #221 is the preferred long term solution anyway. 
2. This scheme can be made compatible with https://github.com/ethereum-optimism/specs/issues/221 by deploying to vanity addresses that have the expected versionByte prefix. However, requiring a vanity address as part of the spec feels leaky and suboptimal. Do we only use this new proposal until #221 is implemented?

**Comment by tynes** [comment]
I am on board with this as a default but ultimately if we support #221 we will need to have the ability to modify the batch inbox address on the `SystemConfig` and have the `op-node` listen to those modifications.  I am not opinionated on what the default standard is as long as its adopted when people do not explicitly say what their batch inbox is. We could always make the L2 chain id a getter on the system config and not need to worry about encoding it in the batch inbox

A side thought is the batch inbox in a way is a file path in a file system. Nothing super useful or actionable about that statement, just throwing it out there

**Comment by mds1** [comment]
> We could always make the L2 chain id a getter on the system config and not need to worry about encoding it in the batch inbox

I do think we should keep the batch inbox address discoverable via SystemConfig, this way external tools like L2Beat can easily find it to e.g. verify data is actually being posted there.

---

It sounds like we agree with a simple, minimal solution for now as a stopgap for #221. The only place in the specs where the current convention is mentioned is in the standard config, so I'll open a PR to change that to the above proposal
